web: gunicorn config.wsgi --log-file -
release: python manage.py test matching --verbosity=1 && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_data && python manage.py clear_mock_users --yes && python manage.py seed_mock_users
