web: gunicorn config.wsgi --log-file -
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_data && python manage.py seed_mock_users && python manage.py create_support_user && python manage.py backfill_support_matches
