# Generated by Django 4.2.27 on 2026-01-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_date_of_birth_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ask_me_answer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='ask_me_prompt_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_pace',
            field=models.CharField(blank=True, choices=[('ready', 'Ready to meet soon'), ('slow', 'Prefer to chat first'), ('virtual', 'Virtual dates preferred'), ('flexible', 'Open to whatever feels right')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_times',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_pace',
            field=models.CharField(blank=True, choices=[('quick', 'I respond quickly'), ('moderate', 'I respond within a few hours'), ('slow', 'I may take a day or more to respond'), ('variable', 'It depends on my energy/health')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_notes',
            field=models.CharField(blank=True, help_text="Additional notes about scheduling (e.g., 'I have PT on Tuesdays')", max_length=200),
        ),
    ]
