# Generated by Django 4.2.27 on 2026-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_unify_gender_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_photos/'),
        ),
    ]
