# Generated by Django 4.2.27 on 2026-01-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_tag_visibility_and_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookingfor',
            name='relationship_types',
        ),
    ]
