# Generated by Django 4.2.27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_relationship_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_pace',
        ),
    ]
