# Generated by Django 4.2.27 on 2026-05-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_openness_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_interests',
            field=models.JSONField(blank=True, default=list, help_text='User-defined interests, max 5 items, max 20 chars each'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prompt_id',
            field=models.CharField(blank=True, choices=[('laughMost', 'The thing that makes me laugh most is...'), ('perfectSunday', 'My perfect Sunday looks like...'), ('convinced', "I'm convinced that..."), ('custom', 'Write your own')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_intent',
            field=models.CharField(blank=True, choices=[('relationship', 'Looking for a relationship'), ('friendship', 'Looking for friends'), ('unsure', 'Not sure yet')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_notes',
            field=models.CharField(blank=True, help_text="Additional notes about scheduling (e.g., 'I'm a night owl, Fridays work best')", max_length=200),
        ),
    ]
