# Generated by Django 4.2.27 on 2026-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='he', max_length=5),
        ),
    ]
